name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - name: Update Changelog
        run: |
          git fetch --depth 10 origin main
          cat docs/CHANGELOG_TEMPLATE.md > docs/CHANGELOG.md
          git log -n 10 --pretty=format:'%n## %s%n%nDate: [%ad](https://github.com/${{ github.repository }}/commit/%H)%n' --date=short --stat | sed 's/$/  /' >> docs/CHANGELOG.md
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
