name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - run: |
          # Escape special characters for sed
          changelog="$(git log -n 10 --pretty=format:'- [%h](https://github.com/${{ github.repository }}/commit/%H) - %ad%n  * %s%n%n' --date=short --name-status | sed 's/[&/\]/\\&/g')"
    
          # Use awk to replace the placeholder with the changelog
          awk -v changelog="$changelog" '{
            sub(/<!-- CHANGELOG_PLACEHOLDER -->/, changelog);
            print;
          }' docs/CHANGELOG_TEMPLATE.md > docs/CHANGELOG.md

      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
